export const ATTENDANCE_CONFIG = {
  ENTER_RADIUS_METERS: 100,
  EXIT_RADIUS_METERS: 100,
  MAX_ACCURACY_METERS: 100,
  REQUIRED_SAMPLES: 3,
  REQUIRED_DURATION_MS: 5000,
  MAX_SPEED_KMH: 150,
  MAX_SAMPLE_SPREAD_METERS: 50,
};
